name       : python-requests
version    : 2.29.0
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/r/requests/requests-2.29.0.tar.gz : f2e34a75f4749019bb0e3effb66683630e4ffeaf75819fb51bebef1bf5aef059
homepage   : https://requests.readthedocs.io/en/latest/
license    : Apache-2.0
component  : programming.python
summary    : Python HTTP for Humans
description: |
    Requests allows you to send organic, grass-fed HTTP/1.1 requests, without the need for manual labor. There's no need to manually add query strings to your URLs, or to form-encode your POST data. Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.
builddeps  :
    - python-certifi
    - python-chardet
    - python-idna
    - python-pytest
    - python-urllib3
rundeps    :
    - python-certifi
    - python-chardet
    - python-charset-normalizer
    - python-idna
    - python-urllib3
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
    # requires httpbin,mocker
    #python3_test pytest3
