name       : python-requests
version    : 2.22.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/01/62/ddcf76d1d19885e8579acb1b1df26a852b03472c0e46d2b959a714c90608/requests-2.22.0.tar.gz : 11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4
license    : Apache-2.0
component  : programming.python
summary    : Python HTTP for Humans
description: |
    Requests allows you to send organic, grass-fed HTTP/1.1 requests, without the need for manual labor. There's no need to manually add query strings to your URLs, or to form-encode your POST data. Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.
networking : yes
builddeps  :
    - python-certifi
    - python-chardet
    - python-idna
    - python-setuptools
    - python-pytest
    - python-urllib3
    - python-typing
rundeps    :
    - python-certifi
    - python-chardet
    - python-idna
    - python-urllib3
    - python-typing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # requires httpbin
    #python_test pytest
    #python3_test pytest3
