name       : python-requests
version    : 2.21.0
release    : 6
source     :
    - https://github.com/requests/requests/archive/v2.21.0.tar.gz : 9f9a50b5f64f4569704b9c5e618b957109e3486256453c9016c6dbfa10570761
license    : Apache-2.0
component  : programming.python
summary    : Python HTTP for Humans
description: |
    Requests allows you to send organic, grass-fed HTTP/1.1 requests, without the need for manual labor. There's no need to manually add query strings to your URLs, or to form-encode your POST data. Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.
networking : yes
builddeps  :
    - python-certifi
    - python-chardet
    - python-idna
    - python-setuptools
    - python-urllib3
rundeps    :
    - python-certifi
    - python-chardet
    - python-idna
    - python-urllib3
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test