name       : python-requests
version    : 2.11.1
release    : 3
source     :
    - https://pypi.python.org/packages/2e/ad/e627446492cc374c284e82381215dcd9a0a87c4f6e90e9789afefe6da0ad/requests-2.11.1.tar.gz : 5acf980358283faba0b897c73959cecf8b841205bb4b2ad3ef545f46eae1a133
license    : Apache-2.0
component  : programming.python
summary    : Python HTTP for Humans.
description: |
    Python HTTP for Humans.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
