name       : python-requests
version    : 2.7.0
release    : 2
source     :
    - https://pypi.python.org/packages/source/r/requests/requests-2.7.0.tar.gz : 398a3db6d61899d25fd4a06c6ca12051b0ce171d705decd7ed5511517b4bb93d
license    : Apache-2.0
summary    : Python HTTP for Humans.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
description: |
    Python HTTP for Humans.
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
