name       : python-requests
version    : 2.25.1
release    : 9
source     :
    - https://pypi.io/packages/source/r/requests/requests-2.25.1.tar.gz : 27973dd4a904a4f13b263a19c866c13b92a39ed1c964655f025f3f8d3d75b804
license    : Apache-2.0
component  : programming.python
summary    : Python HTTP for Humans
description: |
    Requests allows you to send organic, grass-fed HTTP/1.1 requests, without the need for manual labor. There's no need to manually add query strings to your URLs, or to form-encode your POST data. Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.
builddeps  :
    - python-certifi
    - python-chardet
    - python-idna
    - python-setuptools
    - python-pytest
    - python-urllib3
    - python-typing
rundeps    :
    - python-certifi
    - python-chardet
    - python-idna
    - python-urllib3
    - python-typing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
    # requires httpbin,mocker
    #python_test pytest
    #python3_test pytest3
